filter:
    paths: ["src/*"]
    excluded_paths: ["vendor/*", "tests/*"]
tools:
    php_code_sniffer: true
    php_sim: true
    php_changetracking: true
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd:
      enabled: true
      excluded_dirs: ["vendor", "tests"]
    external_code_coverage: true
    sensiolabs_security_checker: true