build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

filter:
    paths: ["src/*"]
    excluded_paths: ["vendor/*", "tests/*"]
    dependency_paths:
        - "vendor/"
tools:
    php_code_sniffer: true
    php_sim: true
    php_changetracking: true
    php_cs_fixer: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: false
    external_code_coverage: true
    sensiolabs_security_checker: true