sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  include:
    # test against the latest HHVM version by using trusty
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # Use edge image until the next travis CI image update
  allow_failures:
    - php: hhvm

git:
  depth: 5

addons:
  apt:
    packages:
    - postfix

before_install:
  - pip install --user codecov

before_script:
  - composer self-update
  - composer install
  - smtp-sink -d "build/email/%d.%H.%M.%S" 127.0.0.1:2500 1000 &
  - mkdir -p build/logs

after_success:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
  - codecov
  - "CODECLIMATE_REPO_TOKEN=a757d1980821cc8b324859a9755a1c8524c1e00409a8fa00a67acd41a649cf25 ./vendor/bin/test-reporter"